### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by ericgaspar**

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by Binnette** [comment]
Hi @ericgaspar, as written in README, I ran the command `sudo yunohost app install https://github.com/Binnette/selfoss_ynh/tree/testing --debug` on my server (this branch is up to date with yours but contain more logs)

This command failed with error: `33325 ERROR The operation 'Install the 'selfoss' app' could not be completed. Please share the full log of this operation using the command 'yunohost log share 20221223-224827-app_install-selfoss' to get help`

I saw some warning in the log:
```
24583 DEBUG + chmod g+w /var/www/selfoss/data/cache /var/www/selfoss/data/favicons /var/www/selfoss/data/logs /var/www/selfoss/data/thumbnails /var/www/selfoss/data/sqlite /var/www/selfoss/public
24584 WARNING chmod: cannot access '/var/www/selfoss/data/cache': No such file or directory
24585 WARNING chmod: cannot access '/var/www/selfoss/data/favicons': No such file or directory
24585 WARNING chmod: cannot access '/var/www/selfoss/data/logs': No such file or directory
24585 WARNING chmod: cannot access '/var/www/selfoss/data/thumbnails': No such file or directory
24586 WARNING chmod: cannot access '/var/www/selfoss/data/sqlite': No such file or directory
24586 WARNING chmod: cannot access '/var/www/selfoss/public': No such file or directory
```

So I dig those warnings by adding a `pwd` and a `ls $final_path` in the install script. And this is weird. It seems that the zip file of selfoss is "flat" extracted. All the files in the folders of the zip are extracted to /var/www/selfoss/

Here is what my `ls $final_path` (from install script):
```
24500 INFO [##########+.........] > DEBUG pwd
24556 DEBUG + set +o xtrace
24567 DEBUG + echo '! Helper used in legacy mode !'
24567 DEBUG + set +x
24569 DEBUG + echo '[###########+........] > DEBUG ls /var/www/selfoss'
24570 DEBUG + set -o xtrace
24570 DEBUG + ls /var/www/selfoss
24570 INFO [###########+........] > DEBUG ls /var/www/selfoss
24571 DEBUG Anonymizer.php
24572 DEBUG Authentication.php
24572 DEBUG autoload.php
24572 DEBUG badge.phtml
24572 DEBUG BaseController.php
24572 DEBUG bcosca
24572 DEBUG bin
24572 DEBUG cache
24572 DEBUG Color.php
24572 DEBUG composer
24572 DEBUG ContentLoader.php
24572 DEBUG css
24572 DEBUG Database.php
24572 DEBUG ddeboer
24573 DEBUG deviantart
24573 DEBUG electrolinux
24573 DEBUG etc
24573 DEBUG facebook
24573 DEBUG favicon.ico
24573 DEBUG favicons
24573 DEBUG FileNotFoundException.php
24573 DEBUG fonts
24573 DEBUG fossar
24573 DEBUG fulltextrss
24573 DEBUG github
24573 DEBUG guzzlehttp
24573 DEBUG hashpassword.phtml
24573 DEBUG home.phtml
[...]
```

And here is the same ls command when I extract the same zip on my computer:
```
~/Downloads$ ls -1 selfoss-2.18
cliupdate.php
common.php
controllers
daos
data
defaults.ini
helpers
index.php
public
README.md
run.php
spouts
templates
vendor
```

You see? All the files in the subfolders public, template, vendor, etc are extracted to the root /www/var/selfoss.
It should not be extracted like so.

Let me know if you know this "behavior". I will try to read yunohost docs to 'fix' this behavior. We need the zip to be extracted as it, not as a "flat" zip.

**Comment by Binnette** [comment]
Hello @ericgaspar,

- Zip 2.18 do not have any subdirectory for sources
- Zip 2.19 have a 'selfoss' subdirectoty

So I tested your branch testing (I changed `SOURCE_IN_SUBDIR=true` to remove the selfoss folder in zip 2.19), and the package install correctly.

Have a nice day.

**Comment by Binnette** [comment]
Hi @ericgaspar, all steps are "success" but there are still some "linter errors": https://ci-apps-dev.yunohost.org/ci/job/4766

>  ⓘ Configuration files
> 
> For the php configuration, consider getting rid of php-fpm.conf and using the --usage and --footprint option of ynh_add_fpm_config. This will use an auto-generated php conf file.Additionally you can provide a conf/extra_php-fpm.conf for custom PHP settings that will automatically be appended to the autogenerated conf.  (Feel free to discuss this on the chat with other people, the whole thing with --usage/--footprint is legitimately a bit unclear ;))

Let me know if you want me to investigate (/fix) this issue. As far as I understood, I will need to update the install scripts to use ynh_add_fpm_config. So I will probably have a look to example_ynh or maybe wordpress_ynh to see changes that needs to be done.

**Pull request merged**
